apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.8.2.14
  share: /data/nfs/
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: true
# https://microk8s.io/docs/nfs
